### ISSUE TITLE
__download: type can break remote files on abort

### ISSUE THREAD

**Issue by Matze1224** [skonfig/base#33]
> Noticed something other while looking into the code: At local downloads, we don't use any tempfile for the remote side. As I don't think `scp` will do it, we leave a broken target file on a cdist abort. It would be saver to do the same as on remote downloads to first copy it to a tempfile and then move it to the destination.

You are correct. But that makes it more interesting.

1. in gencode-local download to local download_tmp.
2. in gencode-local remote copy from local download_tmp to from remote_copy_tmp.

```
remote_copy_tmp="${dst}.cdist__download_tmp"

# shellcheck disable=SC2016
printf '%s "$download_tmp" %s:%s\n' \
    "$__remote_copy" \
    "$target_host" \
    "$remote_copy_tmp"

echo "rm -f \"\$download_tmp\""
```

3. in gencode-remote mv remote_copy_tmp to dst?

```
???
```

Can we actually do it like this... I have to look into cdist-core...

Or just do `$__remote_exec ...` in gencode-local?

_Originally posted by @4nd3r in https://github.com/cdist-community/cdist-conf/issues/28#issuecomment-1080556338_

---

This behaviour is pretty similar to `__file` and co, but we only need to copy to an tmp file instead of the real file, move the tmp file to the real file (can be done in `gencode-local` via `$__remote_exec` to keep the command flow) and then do the local cleanup.

**Comment by sideeffect42** [comment]
I believe this bug was fixed with #91.
